[package]
name = "nf"
version = "0.1.0"
description = "CLI app to interact with NablaFlow's API"
edition = "2021"
publish = false

[dependencies]
convert_case = "0.7.1"
chrono = { version = "~0.4.39", features = ["serde"] }
clap = { version = "~4.5", features = ["derive", "env"] }
clap-stdin = "0.6.0"
clap_complete = "4.5.42"
clap_mangen = "0.2.26"
color-eyre = { version = "~0.6", default-features = false }
comfy-table = { version = "~7.1.3" }
cynic = { version = "~3.9", features = ["http-reqwest"] }
dirs = "6.0.0"
itertools = "0.14.0"
reqwest = { version = "~0.12", default-features = false, features = ["rustls-tls", "http2", "json", "gzip", "stream"] }
serde = { version = "~1.0", features = ["derive"] }
serde_json = "1.0.137"
termcolor = "1.4.1"
tokio = { version = "~1.43", default-features = false, features = ["rt", "macros", "fs"] }
tracing = "~0.1"
tracing-subscriber = "~0.3"

[build-dependencies]
cynic-codegen = "~3.9.0"

[profile.release]
lto = "thin"

[profile.dev.package.backtrace]
opt-level = 3
