[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.30.2"
ci = "github"
# pr-run-mode = "upload"

include = [
  "examples",
]

installers = [
  "shell",
  "powershell",
  "msi",
]

allow-dirty = [
  "msi",
]

targets = [
  "aarch64-apple-darwin",
  "aarch64-pc-windows-msvc",
  "aarch64-unknown-linux-musl",
  "x86_64-apple-darwin",
  "x86_64-pc-windows-msvc",
  "x86_64-unknown-linux-musl",
]

[dist.github-custom-runners]
aarch64-unknown-linux-musl = "ubuntu-22.04"
aarch64-pc-windows-msvc = "windows-2022"
