name = "my model"
reusable = false # or true

[[files]]
name = "file1"
unit = "m" # or "mm", "cm", "inches"
orientation = [1.0, 0.0, 0.0, 0.0]
path = "examples/aerocloud/v6/ball.stl"

# [[files]]
# name = "file2"
# unit = "m" # or "mm", "cm", "inches"
# orientation = [1.0, 0.0, 0.0, 0.0]
# path = "..."
